---
title: "CovSampling"
author: "Jiaming"
date: "29/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Sample from i.i.d Normal distribution
```{r}
data = mvtnorm::rmvnorm(100, sigma=diag(100))
sampleCov=cov(data)

out1 <- PreEst.banded3(data, upperK=1)
out2 <- PreEst.banded3(data, upperK=3)
out3 <- PreEst.banded3(data, upperK=5)

ggcorrplot(solve(out1$C))
ggcorrplot(solve(out2$C))
ggcorrplot(solve(out3$C))
ggcorrplot(sampleCov)
```


## Sample from correlated Normal distribution
```{r}
Posdef <- function (n, ev = runif(n, 0, 10))
{
  Z <- matrix(ncol=n, rnorm(n^2))
  decomp <- qr(Z)
  Q <- qr.Q(decomp)
  R <- qr.R(decomp)
  d <- diag(R)
  ph <- d / abs(d)
  O <- Q %*% diag(ph)
  Z <- t(O) %*% diag(ev) %*% O
  return(Z)
}
pdmat <- Posdef(n=5, ev=1:5)

Bandit=function(pdmat,k)
{
  n=dim(pdmat)[1]
  for (i in 1:n)
  {
    for (j in 1:n) {
      if (abs(i-j)>k)
       pdmat[i,j]=0
        }
  }
  return (pdmat)
}
```
The tool function for generate random positive definite matrix and bandit matrix.

```{r}
set.seed(10)
#set.seed(1)
data2Cov=Posdef(200)
data2bandCov=Bandit(data2Cov,4)
data2band = mvtnorm::rmvnorm(100, sigma=data2bandCov)
out1 <- PreEst.banded3(data2band, upperK=1)
out2 <- PreEst.banded3(data2band, upperK=5)
out3 <- PreEst.banded3(data2band, upperK=9)
out4=band.chol(data2band,k=10)

ggcorrplot(solve(out1$C))
ggcorrplot(solve(out2$C))
ggcorrplot(solve(out3$C))
out3$optk
ggcorrplot(out4)
ggcorrplot(cov(data2band))
ggcorrplot(data2bandCov)
ggcorrplot(solve(data2bandCov))
ggcorrplot(out2$C)
#solve(data2bandCov)
```

