---
title: "Structure of Review-banded width precision-covariance matrices"
author: "Jiaming"
date: "08/11/2018"
output:
  html_document: default
csl: apa.csl
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
---


断点数据：抄完了 Bayesian Test and Selection for Bandwidth of High-dimensional Banded Precision Matrices 的模型数据。
下一步：要么继续写这篇文章的Hypothesis构造的算法，要么去抄An(2014)和 Cheng(2017）模型构造以及构造细节。

---

阶段性成就数据：抄完了Bayesian Test and Selection for Bandwidth of High-dimensional Banded Precision Matrices 的hypotheses 构造算法，下一步则如上应该抄An(2014)和 Cheng(2017)的模型构造以及构造细节。于是从开始抄模型开始，往"Appendix"中的model specification里面加内容，或者直接加到后面，然后等写完了以后重新排版。

---

阶段性成就数据：抄完了Hypothesis testing for band size detection of high-dimensional banded precision matrices 的数据定义，统计量构造方法，以及算法。
下一步，完成zhang(2017)的对应描述。

After that, 如果有时间，就把这几个算法都实践一遍，至少目前看来Baiguo AN的方法应该相对容易实现。Bayes的话可以等到学习stan等bayes方法工具的时候再说。Zhang的话就等看完再说。

---



---
I start with the [@An:2014jc] which is the frequecy part of the banded-width test, then another approach is done by [@Cheng:2017jh]. The most distinct part between these two approach is the cholesky decomposition. 

(I need figure out who don't use this.) 

